version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  ApplicationStop:
    - location: stop_server.sh
  BeforeInstall:
    - location: install_dependencies.sh
  ApplicationStart:
    - location: start_server.sh
  ValidateService:
    - location: verify_response.sh
